In [19]:
%timeit [j**4 for j in range(1,9)]

1.76 µs ± 43.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [17]:
import numpy as np
%timeit np.arange(1,9)**4

1.61 µs ± 22.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [2]:
import numpy as np
x=[1,2,3,5]
y=np.array([1,2,3,4,5])
print(y)
print(type(y))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [15]:
l=[]

for i in range(1,5):
    int_1=int(input("enter : "))
    l.append(int_1)
    
print(np.array(l))   

enter : 45
enter : 67
enter : 87
enter : 12
[45 67 87 12]


In [14]:
import numpy as np
ar3=np.array([[[1,2,3],[1,4,5],[1,7,8]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3]
  [1 4 5]
  [1 7 8]]]
3


In [13]:
arn=np.array([1,2,3,4].ndmin=10)
print(arn)
print(arn.ndim)


SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (3006133081.py, line 1)

In [12]:
arn=np.array([1,2,3,4],ndmin=10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


# ones

In [11]:
ar_one=np.ones(4)
print(ar_one)


[1. 1. 1. 1.]


# empty

In [10]:
ar_em=np.empty(4)
print(ar_em)

[ 5. 10. 15. 20.]


# range

In [9]:
ar_rn=np.arange(5)
print(ar_rn)

[0 1 2 3 4]


# diagonal

In [8]:
ar_dia=np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
ar_dia=np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# linespace

In [6]:
ar_lin=np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


# random

In [2]:
import numpy as np
var=np.random.randn(2,5)
print(var)

[[-0.0762446   1.38626506  0.91390234  1.54539215  0.27904722]
 [ 1.31334525  0.40768271 -1.66448815  1.74808664 -1.05457936]]


In [3]:
var1=np.random.rand(2,5)
print(var1)

[[0.44157522 0.23533552 0.73036976 0.01422851 0.87884414]
 [0.03487657 0.3464118  0.61854046 0.79150828 0.94000338]]


In [22]:
var3=np.random.ranf(4)
print(var3)

[0.69165273 0.16739681 0.70028249 0.62198476]


In [21]:
var4=np.randint(5,20,5)
print(var4)


AttributeError: module 'numpy' has no attribute 'randint'

# DATA types

In [23]:
var=np.array([1.0,2.0,4.5])
print("Data type:",var.dtype)

Data type: float64


In [24]:
var=np.array([1,2,3,5,14])
print("Data type:",var.dtype)

Data type: int32


In [25]:
var=np.array(["a","S","T","p"])
print("Data type:",var.dtype)

Data type: <U1


In [28]:
x=np.array([1,2,3,4],dtype=np.int8)
print("Data type",x.dtype)

Data type int8


In [3]:
x2=np.array([1,2,3,4])
new=np.float32(x2)
new_one=np.int_(new)
print("Data type:",x2.dtype)
print("Data type:",new.dtype)
print("Data type:",new.dtype)
print("Data type:",new_one.dtype)

print(x2)
print(new)
print(new_one)

Data type: int32
Data type: float32
Data type: float32
Data type: int32
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [4]:
x3=np.array([1,2,3,4])
new_1=x3.astype(float)

print(x3)
print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]


In [7]:
var=np.array([[1,2,3,4],[1,2,3,4]])
print(var)
print()
print(var.shape)

[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


In [9]:
var1=np.array([1,2,3,4],ndmin=4)
print(var1)
print(var1.ndim)
print(var1.shape)

[[[[1 2 3 4]]]]
4
(1, 1, 1, 4)


In [10]:
#[1,2,3,4]-> denotes to rows and 4(is elemnts)(1,2,3,4) denotes columns

# reshape

In [18]:
var2= np.array([1,2,3,4,5,6])
#var3=np.array([1,2,3,4,5,6[1,2,9]])
print(var2)
print(var2.ndim)

print()
#print(var3)

x=var2.reshape(3,2)
#x1=var.reshape(3,3)
print(x)
print(x.ndim)

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


In [26]:
var3= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(var3.ndim)

print()
#print(var3)

x=var3.reshape(3,2,2)
print(x)
print(x.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
3


In [27]:
var3= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(var3.ndim)

print()
#print(var3)

x=var3.reshape(3,2,2)
print(x)
print(x.ndim)

one=x.reshape(-1)
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
3
[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


# Arithmatic operation

In [28]:
var=np.array([1,2,3,4])
varadd=var + 3
print(varadd)

[4 5 6 7]


In [29]:
var1=np.array([1,2,3,4])
var2=np.array([1,4,5,8])
varadd=var1+var2
print(varadd)

[ 2  6  8 12]


In [30]:
var1=np.array([1,2,3,4])
var2=np.array([1,4,5,8])
varadd=var1*var2
print(varadd)

[ 1  8 15 32]


In [31]:
var=np.array([1,2,3,4])
varadd=var / 3
print(varadd)

[0.33333333 0.66666667 1.         1.33333333]


In [32]:
var=np.array([1,2,3,4])
varadd=var % 3
print(varadd)

[1 2 0 1]


In [42]:
var=np.array([1,2,3,4])
var1=
print(var1)

TypeError: remainder() takes from 2 to 3 positional arguments but 1 were given

In [37]:
var1=np.array([1,2,3,4])
var2=np.array([1,4,5,8])
varadd=np.multiply(var1,var2)
print(varadd)

[ 1  8 15 32]


In [39]:
var=np.array([1,2,3,4])
varadd=np.reciprocal(var)
print(varadd)

[1 0 0 0]


In [35]:
var1=np.array([1,2,3,4])
var2=np.array([1,4,5,8])
varadd=np.add(var1,var2)
print(varadd)

[ 2  6  8 12]


# 2d array

In [38]:
var21=np.array([[1,2,3,4],[2,4,5,9]])
var22=np.array([[1,2,3,4],[2,4,5,9]])

print(var21)
print()
print(var22)
print()

varadd2= var21+ var22
print(varadd2)

[[1 2 3 4]
 [2 4 5 9]]

[[1 2 3 4]
 [2 4 5 9]]

[[ 2  4  6  8]
 [ 4  8 10 18]]


In [46]:
var=np.array([1,7,8,5,6,4,3])
print("min:",np.min(var))
print("max:",np.max(var))
print("min:",np.min(var),np.argmin(var))
print("max:",np.max(var),np.argmax(var))

min: 1 0
max: 8 2


In [47]:
var1=np.array([[2,1,3],[2,5,6]])
print(np.min(var1,axis=1))

[1 2]


In [48]:
var1=np.array([[2,1,3],[2,5,6]])
print(np.min(var1,axis=0))

[2 1 3]


In [49]:
var=np.array([1,7,8,5,6,4,3])
print("sqrt:",np.sqrt(var))

sqrt: [1.         2.64575131 2.82842712 2.23606798 2.44948974 2.
 1.73205081]


In [50]:
var=np.array([1,7,8,5,6,4,3])
print(np.sin(var))

[ 0.84147098  0.6569866   0.98935825 -0.95892427 -0.2794155  -0.7568025
  0.14112001]


In [51]:
var=np.array([1,7,8,5,6,4,3])
print(np.cos(var))

[ 0.54030231  0.75390225 -0.14550003  0.28366219  0.96017029 -0.65364362
 -0.9899925 ]


In [52]:
var=np.array([1,2,3])
print(np.cumsum(var))

[1 3 6]


# brodcasting numpy

In [55]:
var1=np.array([1,2,3])
print(var1.shape)
print()
print(var1)
print()

var2=np.array([[1],[2],[3]])
print(var2.shape)
print()
print(var2)

print()
print(var1+var2)


(3,)

[1 2 3]

(3, 1)

[[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]


# slicing


In [70]:
var=np.array([1,2,3,4,5,6])
print(var)

print()

print("2 to 5:",var[1:4])
print("2 to end:",var[1:])
print("start to 5:",var[:5])
print("stop:", var[::3])
print("stop:",var[1:6:2])

[1 2 3 4 5 6]

2 to 5: [2 3 4]
2 to end: [2 3 4 5 6]
start to 5: [1 2 3 4 5]
stop: [1 4]
stop: [2 4 6]


In [74]:
var1=np.array([[1,2,3,6],[6,8,4,9],[8,1,5,4]])
print(var1)
print()

print("8 to 9:",var1[0,1:])

[[1 2 3 6]
 [6 8 4 9]
 [8 1 5 4]]

8 to 9: [2 3 6]


# itaration

In [77]:
var=np.array([9,6,7,4,1,5])
print(var)
print()

for i in var:
    print(i)

[9 6 7 4 1 5]

9
6
7
4
1
5


In [79]:
var=np.array([[9,6,7,4,1,5],[9,6,5,3,2,1]])
print(var)
print()

for j in var:
    print(j)
print()

for k in var:
    for l in k:
        print(l)

[[9 6 7 4 1 5]
 [9 6 5 3 2 1]]

[9 6 7 4 1 5]
[9 6 5 3 2 1]

9
6
7
4
1
5
9
6
5
3
2
1


In [82]:
var3=np.array([[[1,4,8],[1,9,6],[8,6,5]]])
print(var3)
print()
print(var3.ndim)

print()
for i in var3:
    for j in i:
        for k in j:
            print(k)

[[[1 4 8]
  [1 9 6]
  [8 6 5]]]

3

1
4
8
1
9
6
8
6
5


In [85]:
var3=np.array([[[1,4,8],[1,9,6],[8,6,5]]])
print(var3)
print()
print(var3.ndim)

for i in np.nditer(var3):
    print(i)
    

print()  
for i,d in np.ndenumerate(var3):
    print(i,d)

[[[1 4 8]
  [1 9 6]
  [8 6 5]]]

3
1
4
8
1
9
6
8
6
5

(0, 0, 0) 1
(0, 0, 1) 4
(0, 0, 2) 8
(0, 1, 0) 1
(0, 1, 1) 9
(0, 1, 2) 6
(0, 2, 0) 8
(0, 2, 1) 6
(0, 2, 2) 5


In [4]:
import numpy as np
var= np.array([1,2,3])
co= var.copy()

var[2]=40

print("var :", var)
print("co :",co)

var : [ 1  2 40]
co : [1 2 3]


In [5]:
x=np.array([9,8,7,6,5])
vi=x.view()

vi[2]= 40 

print("x :" ,x)
print("view : ", vi)

x : [ 9  8 40  6  5]
view :  [ 9  8 40  6  5]


# JOIN and split

In [7]:
import numpy as np
var= np.array([1,2,3,4])
var1=np.array([3,4,6,7])

ar= np.concatenate((var1,var))
print(ar)

[3 4 6 7 1 2 3 4]


In [8]:
import numpy as np
var=np.array([[1,2],[3,5]])
var1=np.array([[1,9],[2,3]])

ar_new=np.concatenate((var,var1),axis=1)

print(var)
print()
print(var)
print()
print(ar_new)

[[1 2]
 [3 5]]

[[1 2]
 [3 5]]

[[1 2 1 9]
 [3 5 2 3]]


In [9]:
var_1=np.array([1,2,3,4])
var_2=np.array([9,8,7,6])
a_new=np.dstack((var_1,var_2)) #HEIGHT
print(a_new)

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]


In [15]:
var_1=np.array([1,2,3,4])
var_2=np.array([9,8,7,6])
a_new=np.stack((var_1,var_2),axis=1) 
a_new1=np.vstack((var_1,var_2))  #col
a_new2=np.hstack((var_1,var_2))  #row
print(a_new)
print()
print(a_new1)
print()
print(a_new2)

[[1 9]
 [2 8]
 [3 7]
 [4 6]]

[[1 2 3 4]
 [9 8 7 6]]

[1 2 3 4 9 8 7 6]


# SPLIT ARRAY

In [17]:
import numpy as np
var= np.array([1,2,3,7,8,9])
print(var)

ar=np.array_split(var,3)
print(type(ar))
print()
print(ar)
print(ar[0])


[1 2 3 7 8 9]
<class 'list'>

[array([1, 2]), array([3, 7]), array([8, 9])]
[1 2]


In [21]:
var1=np.array([[1,2,3],[2,6,7]])
print(var1)

ar=np.array_split(var1,2)
ar1=np.array_split(var1,2,axis=1)
print()
print(ar)
print()
print(ar1)


[[1 2 3]
 [2 6 7]]

[array([[1, 2, 3]]), array([[2, 6, 7]])]

[array([[1, 2],
       [2, 6]]), array([[3],
       [7]])]


# search elements

In [23]:
var=np.array([1,3,4,5,5,2,5,7])

x=np.where(var==5)
print(x)

(array([3, 4, 6], dtype=int64),)


In [25]:
var=np.array([1,3,4,5,5,2,5,7])

x=np.where(var%2 == 0)
print(x)

(array([2, 5], dtype=int64),)


# SORT

In [26]:
var1= np.array([1,2,3,4,6,7,8,9])
x=np.searchsorted(var1,5,side="right")
print(x)

4


In [27]:
var1= np.array([1,2,3,4,6,7,8,9])
x=np.searchsorted(var1,[5,6,7],side="right")
print(x)

[4 5 6]


# sorted array

In [28]:
var_1=np.array([1,7,3,5,45,9,2,77])
print(np.sort(var_1))

[ 1  2  3  5  7  9 45 77]


In [29]:
var_1=np.array([[1,4,5],[2,1,56],[8,3,98]])
print(np.sort(var_1))

[[ 1  4  5]
 [ 1  2 56]
 [ 3  8 98]]


# shuffle

In [30]:
var=np.array([1,2,3,4,8,7])

np.random.shuffle(var)

print(var)

[1 2 7 8 3 4]


# unique

In [31]:
var1=np.array([1,2,3,4,9,4,2,9,5])
x=np.unique(var1)
print(var1)

[1 2 3 4 9 4 2 9 5]


In [38]:
var1=np.array([1,2,3,4,9,2,2,7,5])
x=np.unique(var1,return_index=True,return_counts=True)
print(var1)
print(x)

[1 2 3 4 9 2 2 7 5]
(array([1, 2, 3, 4, 5, 7, 9]), array([0, 1, 2, 3, 8, 7, 4], dtype=int64), array([1, 3, 1, 1, 1, 1, 1], dtype=int64))


In [39]:
var2=np.array([1,2,3,4,5,6])
y=np.resize(var2,(3,2))
print(y)

[[1 2]
 [3 4]
 [5 6]]


In [47]:
var2=np.array([1,2,3,4,5,6])
y=np.resize(var2,(3,2))
print(y)
print()
print(y.flatten())

print(y.flatten(order="F"))
print()
print(y.flatten(order="c"))

print()

print("Ravel :",np.ravel(y,order="F"))


[[1 2]
 [3 4]
 [5 6]]

[1 2 3 4 5 6]
[1 3 5 2 4 6]

[1 2 3 4 5 6]

Ravel : [1 3 5 2 4 6]


# delete

In [49]:
var=np.array([2,8,9,7])
print(var)
v=np.delete(var,3)
print(v)

[2 8 9 7]
[2 8 9]


# matrix

In [51]:
var=np.matrix([[1,3,4],[3,5,6]])
print(var)
print()
print(type(var))

[[1 3 4]
 [3 5 6]]

<class 'numpy.matrix'>


In [52]:
print(np.transpose(var))

[[1 3]
 [3 5]
 [4 6]]


In [53]:
print(var.T)

[[1 3]
 [3 5]
 [4 6]]


In [54]:
var2=np.matrix([[1,2],[3,4]])
print(var2)
print()
print(np.swapaxes(var2,0,1))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [3]:
import numpy as np
var1=np.matrix([1,2,3],[1,3,4])
var2=np.matrix([[1,5,9],[3,5,6]])
print(var1)
print(var1 + var2)

TypeError: Field elements must be 2- or 3-tuples, got '1'